### ISSUE TITLE
Definitely interesting

### ISSUE THREAD

**Issue by cryptid11** [BTCChina/btcchina-websocket-api-python#3]
I really need something printing

`Connected!
Connected!
Connected!
Connected!
Connected!
`

After installing something like 5 dependencies... Can I do something to let it be more interesting?

**Comment by silence-vin** [comment]
@cryptid11 Hi, the sample code do have a connection result print when it connected. Frankly I don't understand your requirement, would you please be more particular?

**Comment by cryptid11** [comment]
I simply expect some useful data to be printed and maybe an example of a way on how to handle them in real time, ok this is the first time I try to use them, but this really seems cryptic on usage.
